// Package deploy turns a locally stored project directory into something a
// worker can build and run: it validates the project type, copies it to a
// scratch directory without the heavy build artefacts, makes sure a Dockerfile
// exists, and packs the result into a tar.gz for shipping over the wire.
package deploy

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	// DockerfileName is the file a worker builds from.
	DockerfileName = "Dockerfile"
	// ComposeFileName is the file a worker runs when present.
	ComposeFileName = "docker-compose.yml"

	// UnsupportedMsg is the user facing error for a project we cannot deploy.
	UnsupportedMsg = "only node apps or js frontend apps are supported: expected a package.json or package-lock.json in the project directory"

	// GeneratedDockerfile is written when the project does not ship one.
	GeneratedDockerfile = `# Generated by controlplane: no Dockerfile was found in the project.
FROM node:22-alpine

WORKDIR /app

# Install dependencies first so this layer caches across source changes.
COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "start"]
`
)

// skippedDirs are never copied into the staged project: dependencies are
// reinstalled inside the image and VCS history is not needed to build.
var skippedDirs = map[string]bool{
	"node_modules": true,
	".git":         true,
}

// IsNodeProject reports whether dir holds a node/js project, i.e. it contains a
// package.json or package-lock.json.
func IsNodeProject(dir string) (bool, error) {
	info, err := os.Stat(dir)
	if err != nil {
		return false, err
	}
	if !info.IsDir() {
		return false, fmt.Errorf("%s is not a directory", dir)
	}

	for _, name := range []string{"package.json", "package-lock.json"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			return true, nil
		}
	}
	return false, nil
}

// Stage copies srcDir into destDir, skipping node_modules and .git. destDir is
// created if needed and is expected to be a fresh directory.
func Stage(srcDir, destDir string) error {
	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return fmt.Errorf("creating staging dir: %w", err)
	}

	return filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(srcDir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		if info.IsDir() && skippedDirs[info.Name()] {
			return filepath.SkipDir
		}

		target := filepath.Join(destDir, rel)

		switch {
		case info.IsDir():
			return os.MkdirAll(target, info.Mode().Perm())
		case info.Mode()&os.ModeSymlink != 0:
			// Symlinks could point anywhere on the worker, so skip them.
			return nil
		case !info.Mode().IsRegular():
			return nil
		default:
			return copyFile(path, target, info.Mode().Perm())
		}
	})
}

func copyFile(src, dst string, mode os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

// EnsureDockerfile writes a Dockerfile and compose file when the project does
// not already have them. project names the image in the generated compose file;
// it is passed in rather than derived from dir because the project is staged in
// a scratch directory whose name is meaningless. It returns the names of the
// files it created.
func EnsureDockerfile(dir, project string) ([]string, error) {
	var created []string

	dockerfile := filepath.Join(dir, DockerfileName)
	if _, err := os.Stat(dockerfile); os.IsNotExist(err) {
		if err := os.WriteFile(dockerfile, []byte(GeneratedDockerfile), 0o644); err != nil {
			return created, fmt.Errorf("writing %s: %w", DockerfileName, err)
		}
		created = append(created, DockerfileName)
	} else if err != nil {
		return created, err
	}

	compose := filepath.Join(dir, ComposeFileName)
	if _, err := os.Stat(compose); os.IsNotExist(err) {
		body := fmt.Sprintf("services:\n  app:\n    build: .\n    image: %s:latest\n", project)
		if err := os.WriteFile(compose, []byte(body), 0o644); err != nil {
			return created, fmt.Errorf("writing %s: %w", ComposeFileName, err)
		}
		created = append(created, ComposeFileName)
	} else if err != nil {
		return created, err
	}

	return created, nil
}

// Archive packs dir into an in-memory tar.gz, which is what gets shipped to a
// worker. node_modules and .git are skipped, matching Stage.
func Archive(dir string) ([]byte, error) {
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)

	walkErr := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		if info.IsDir() && skippedDirs[info.Name()] {
			return filepath.SkipDir
		}
		if !info.Mode().IsRegular() && !info.IsDir() {
			return nil
		}

		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = filepath.ToSlash(rel)
		if info.IsDir() {
			hdr.Name += "/"
		}
		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return nil
		}

		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()

		_, err = io.Copy(tw, f)
		return err
	})

	if walkErr != nil {
		return nil, walkErr
	}
	if err := tw.Close(); err != nil {
		return nil, err
	}
	if err := gz.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// ProjectName derives a container/image safe name from a directory path.
func ProjectName(dir string) string {
	name := strings.ToLower(filepath.Base(filepath.Clean(dir)))
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "project"
	}
	return out
}

// ResolveProjectRoot returns the directory that actually holds the project.
//
// GitHub's tarball endpoint wraps everything in a single "owner-repo-sha"
// directory, while an archive produced by Archive has the project at the top
// level. Descending through single-child directories handles both without the
// caller having to know which source it came from.
func ResolveProjectRoot(dir string) (string, error) {
	current := dir
	for depth := 0; depth < 4; depth++ {
		if ok, _ := IsNodeProject(current); ok {
			return current, nil
		}

		entries, err := os.ReadDir(current)
		if err != nil {
			return "", err
		}
		var subdirs []string
		for _, e := range entries {
			if e.IsDir() && !skippedDirs[e.Name()] {
				subdirs = append(subdirs, e.Name())
			}
		}
		if len(subdirs) != 1 {
			return "", fmt.Errorf("%s", UnsupportedMsg)
		}
		current = filepath.Join(current, subdirs[0])
	}
	return "", fmt.Errorf("could not find the project root under %s: %s", dir, UnsupportedMsg)
}

// Unpack extracts a tar.gz produced by Archive into destDir. Entries that would
// escape destDir are rejected.
func Unpack(archive []byte, destDir string) error {
	return UnpackTarGz(bytes.NewReader(archive), destDir, false)
}

// UnpackTarGz streams a tar.gz into destDir. Nothing is buffered in memory, so
// this works for archives piped straight off the network.
//
// stripTopDir drops the first path component of every entry. GitHub's tarball
// endpoint wraps the whole repo in a single "owner-repo-sha/" directory, and
// that wrapper would otherwise end up as a stray directory in the project.
//
// Entries that would escape destDir are rejected.
func UnpackTarGz(r io.Reader, destDir string, stripTopDir bool) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return fmt.Errorf("reading archive: %w", err)
	}
	defer gz.Close()

	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return err
	}
	root := filepath.Clean(destDir)

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return fmt.Errorf("reading archive entry: %w", err)
		}

		name := hdr.Name
		if stripTopDir {
			if i := strings.IndexByte(name, '/'); i >= 0 {
				name = name[i+1:]
			} else {
				// The top level directory entry itself.
				continue
			}
			if name == "" {
				continue
			}
		}

		target := filepath.Join(root, filepath.FromSlash(name))
		if target != root && !strings.HasPrefix(target, root+string(os.PathSeparator)) {
			return fmt.Errorf("archive entry %q escapes the target directory", hdr.Name)
		}

		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				return err
			}
			if err := f.Close(); err != nil {
				return err
			}
		}
	}
}
