//THIS IS A SAMPLE PROTO FILE. THE GOAL IS TO JUST INITALLY SETUP GRPC SERVER AND MTLS COMMUNICATION
// BETWEEN CLIENT AND SERVER

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: pkg/proto/config.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoService_Echo_FullMethodName = "/echo.EchoService/Echo"
)

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoServiceClient(cc grpc.ClientConnInterface) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, EchoService_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServiceServer is the server API for EchoService service.
// All implementations must embed UnimplementedEchoServiceServer
// for forward compatibility.
type EchoServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedEchoServiceServer()
}

// UnimplementedEchoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoServiceServer struct{}

func (UnimplementedEchoServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoServiceServer) mustEmbedUnimplementedEchoServiceServer() {}
func (UnimplementedEchoServiceServer) testEmbeddedByValue()                     {}

// UnsafeEchoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServiceServer will
// result in compilation errors.
type UnsafeEchoServiceServer interface {
	mustEmbedUnimplementedEchoServiceServer()
}

func RegisterEchoServiceServer(s grpc.ServiceRegistrar, srv EchoServiceServer) {
	// If the following call panics, it indicates UnimplementedEchoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoService_ServiceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoService_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoService_ServiceDesc is the grpc.ServiceDesc for EchoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/config.proto",
}

const (
	RegisterWorker_Register_FullMethodName = "/echo.RegisterWorker/Register"
)

// RegisterWorkerClient is the client API for RegisterWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterWorkerClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterWorkerRequest, RegisterWorkerResponse], error)
}

type registerWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterWorkerClient(cc grpc.ClientConnInterface) RegisterWorkerClient {
	return &registerWorkerClient{cc}
}

func (c *registerWorkerClient) Register(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegisterWorkerRequest, RegisterWorkerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RegisterWorker_ServiceDesc.Streams[0], RegisterWorker_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterWorkerRequest, RegisterWorkerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegisterWorker_RegisterClient = grpc.BidiStreamingClient[RegisterWorkerRequest, RegisterWorkerResponse]

// RegisterWorkerServer is the server API for RegisterWorker service.
// All implementations must embed UnimplementedRegisterWorkerServer
// for forward compatibility.
type RegisterWorkerServer interface {
	Register(grpc.BidiStreamingServer[RegisterWorkerRequest, RegisterWorkerResponse]) error
	mustEmbedUnimplementedRegisterWorkerServer()
}

// UnimplementedRegisterWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegisterWorkerServer struct{}

func (UnimplementedRegisterWorkerServer) Register(grpc.BidiStreamingServer[RegisterWorkerRequest, RegisterWorkerResponse]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegisterWorkerServer) mustEmbedUnimplementedRegisterWorkerServer() {}
func (UnimplementedRegisterWorkerServer) testEmbeddedByValue()                        {}

// UnsafeRegisterWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterWorkerServer will
// result in compilation errors.
type UnsafeRegisterWorkerServer interface {
	mustEmbedUnimplementedRegisterWorkerServer()
}

func RegisterRegisterWorkerServer(s grpc.ServiceRegistrar, srv RegisterWorkerServer) {
	// If the following call panics, it indicates UnimplementedRegisterWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegisterWorker_ServiceDesc, srv)
}

func _RegisterWorker_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RegisterWorkerServer).Register(&grpc.GenericServerStream[RegisterWorkerRequest, RegisterWorkerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegisterWorker_RegisterServer = grpc.BidiStreamingServer[RegisterWorkerRequest, RegisterWorkerResponse]

// RegisterWorker_ServiceDesc is the grpc.ServiceDesc for RegisterWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.RegisterWorker",
	HandlerType: (*RegisterWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _RegisterWorker_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/config.proto",
}
