//THIS IS A SAMPLE PROTO FILE. THE GOAL IS TO JUST INITALLY SETUP GRPC SERVER AND MTLS COMMUNICATION
// BETWEEN CLIENT AND SERVER

syntax = "proto3";
package echo;
option go_package="./pb";

message EchoRequest{
    string message=1;
}
message EchoResponse{
    string message=1;
}

service EchoService{
rpc Echo(EchoRequest) returns (EchoResponse);
}

message RegisterWorkerRequest{
    string name=1;
     sint32 heartbeat=2;
}
message RegisterWorkerResponse{
    string task=1;
    bool success=2;
}
service RegisterWorker{
    rpc Register(stream RegisterWorkerRequest) returns (stream RegisterWorkerResponse);
}
